export const IpcChannel = {
  SettingsGet: 'settings:get',
  SettingsUpdate: 'settings:update',
  KeyStatus: 'key:status',
  KeyValidateAndStore: 'key:validateAndStore',
  KeyClear: 'key:clear',
  StorageListConversations: 'storage:listConversations',
  StorageGetConversation: 'storage:getConversation',
  StorageCreateConversation: 'storage:createConversation',
  StorageRenameConversation: 'storage:renameConversation',
  StorageDeleteConversation: 'storage:deleteConversation',
  StorageAppendMessage: 'storage:appendMessage',
  MemoryList: 'memory:list',
  MemoryAdd: 'memory:add',
  MemoryUpdate: 'memory:update',
  MemoryDelete: 'memory:delete',
  MemoryClear: 'memory:clear',
  AnthropicSend: 'anthropic:send',
  AnthropicCancel: 'anthropic:cancel',
  AnthropicChunk: 'anthropic:chunk',
  AnthropicDone: 'anthropic:done',
  AnthropicError: 'anthropic:error',
  SystemOpenExternal: 'system:openExternal',
} as const;
