name: Run Report
on:
  workflow_dispatch:

jobs:
  run-report:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell Script
        shell: pwsh
        run: |
          ./powershell/Get-DateReport.ps1
